#cloud-config
debug:
  verbose: true
cloud_init_modules:
 - migrator
 - seed_random
 - write-files
 - growpart
 - resizefs
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - users-groups
 - ssh
 - runcmd
users:
  - name: user
    groups: sudo
    lock_passwd: false
    passwd: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    expire: False
chpasswd:
  list:
    - "user:user"
  expire: False

timezone: "Europe/Moscow"
fqdn: "rabbitmq"

runcmd:
  - sudo -i 
  - mkdir -p /opt/rabbitmq
  - cd /opt/rabbitmq
  - git clone https://github.com/Gellerti/cloud.git .
  - chmod -R 777 /opt/rabbitmq
  - echo 'export PASSWORD=12345' | tee -a /etc/profile
  - source /etc/profile
  - ./opt/rabbitmq/install_rabbitmq.sh -i

